CREATE TABLE Users (
	USERID INTEGER PRIMARY KEY,
	USERNAME VARCHAR ( 255 ),
	EMAIL VARCHAR ( 255 ),
	PASSWORD VARCHAR ( 255 ) 
);
CREATE TABLE Airlines (
	IATA_CODE VARCHAR ( 2 ) PRIMARY KEY,
	AIRLINE VARCHAR ( 255 ) 
);
CREATE TABLE Airports (
	IATA_CODE VARCHAR ( 3 ) PRIMARY KEY,
	AIRPORT VARCHAR ( 255 ),
	CITY VARCHAR ( 255 ),
	STATE VARCHAR ( 2 ),
	COUNTRY VARCHAR ( 255 ),
	LATITUDE REAL,
	LONGITUDE REAL 
);
CREATE TABLE Serve (
	IATA_AIRPORT VARCHAR ( 3 ) REFERENCES Airports ( IATA_CODE ),
	IATA_AIRLINE VARCHAR ( 2 ) REFERENCES Airlines ( IATA_CODE ),
	PRIMARY KEY ( IATA_AIRPORT, IATA_AIRLINE ) 
);
CREATE TABLE Flights (
	YEAR INTEGER,
	MONTH INTEGER,
	DAY INTEGER,
	DAY_OF_WEEK INTEGER,
	AIRLINE VARCHAR ( 2 ) REFERENCES Airlines ( IATA_CODE ) ON DELETE CASCADE,
	FLIGHT_NUMBER VARCHAR ( 255 ),
	TAIL_NUMBER VARCHAR ( 255 ),
	ORIGIN_AIRPORT VARCHAR ( 3 ) REFERENCES Airports ( IATA_CODE ) ON DELETE CASCADE,
	DESTINATION_AIRPORT VARCHAR ( 3 ),
	SCHEDULED_DEPARTURE INTEGER,
	DEPARTURE_TIME INTEGER,
	DEPARTURE_DELAY INTEGER,
	TAXI_OUT INTEGER,
	WHEELS_OFF INTEGER,
	SCHEDULED_TIME INTEGER,
	ELAPSED_TIME INTEGER,
	AIR_TIME INTEGER,
	DISTANCE INTEGER,
	WHEELS_ON INTEGER,
	TAXI_IN INTEGER,
	SCHEDULED_ARRIVAL INTEGER,
	ARRIVAL_TIME INTEGER,
	ARRIVAL_DELAY INTEGER,
	DIVERTED BOOL,
	CANCELLED BOOL,
	CANCELLATION_REASON CHAR,
	AIR_SYSTEM_DELAY INTEGER,
	SECURITY_DELAY INTEGER,
	AIRLINE_DELAY INTEGER,
	LATE_AIRCRAFT_DELAY INTEGER,
	WEATHER_DELAY INTEGER,
	PRIMARY KEY ( YEAR, MONTH, DAY, FLIGHT_NUMBER, AIRLINE ) 
);
CREATE TABLE Feedbacks (
	FEEDBACKID INTEGER PRIMARY KEY,
	USERID INTEGER REFERENCES Users ( USERID ) ON DELETE CASCADE,
	YEAR INTEGER,
	MONTH INTEGER,
	DAY INTEGER,
	FLIGHT_NUMBER VARCHAR ( 255 ),
	AIRLINE VARCHAR ( 2 ),
	CONTENT VARCHAR ( 255 ),
FOREIGN KEY ( YEAR, MONTH, DAY, FLIGHT_NUMBER, AIRLINE ) REFERENCES Flights ( YEAR, MONTH, DAY, FLIGHT_NUMBER, AIRLINE ) ON DELETE CASCADE 
);